 **Modelo de Regressão Linear / USA-Housing-Dataset**

In [ ]:
#Importando bibliiotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
#Importando a base
!wget https://raw.githubusercontent.com/cedmenezes/estudos/refs/heads/main/USA_Housing.csv

--2026-03-06 11:49:46--  https://raw.githubusercontent.com/cedmenezes/estudos/refs/heads/main/USA_Housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 726209 (709K) [text/plain]
Saving to: ‘USA_Housing.csv’

USA_Housing.csv     100%[===================>] 709.19K  --.-KB/s    in 0.007s

2026-03-06 11:49:46 (97.5 MB/s) - ‘USA_Housing.csv’ saved [726209/726209]

In [ ]:
# lendo o arquivo USA_Housing.csv
df = pd.read_csv('USA_Housing.csv')


# Exibindo as colunas
df.columns

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price', 'Address'],
      dtype='object')

In [ ]:
# verificando as primeiras instâncias
df.head()


# identificar o tipo de cada variável
df.dtypes

Avg. Area Income                float64
Avg. Area House Age             float64
Avg. Area Number of Rooms       float64
Avg. Area Number of Bedrooms    float64
Area Population                 float64
Price                           float64
Address                          object
dtype: object

**Normalizando os dados**

In [ ]:
# excluir a coluna endereço
df.drop('Address',axis=1,inplace=True)

In [ ]:
df

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05
...,...,...,...,...,...,...
4995,60567.944140,7.830362,6.137356,3.46,22837.361035,1.060194e+06
4996,78491.275435,6.999135,6.576763,4.02,25616.115489,1.482618e+06
4997,63390.686886,7.250591,4.805081,2.13,33266.145490,1.030730e+06
4998,68001.331235,5.534388,7.130144,5.44,42625.620156,1.198657e+06
4999,65510.581804,5.992305,6.792336,4.07,46501.283803,1.298950e+06

**Aplicando o Modelo de Regressão Linear**  
Vamos agora começar a treinar o modelo de regressão! Primeiro, precisamos dividir nossos dados em uma matriz X que contém os recursos para treinamento e uma matriz y com a variável de destino, neste caso a coluna Preço. Jogaremos fora a coluna Endereço, pois ela possui apenas informações de texto que o modelo de regressão linear não pode usar.  
Matriz X e y  
**X - variáveis preditoras**  
**Y - variável de resposta**

In [ ]:
X = df[['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms','Avg. Area Number of Bedrooms', 'Area Population']]
y = df['Price']
X.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population
0,79545.458574,5.682861,7.009188,4.09,23086.800503
1,79248.642455,6.002900,6.730821,3.09,40173.072174
2,61287.067179,5.865890,8.512727,5.13,36882.159400
3,63345.240046,7.188236,5.586729,3.26,34310.242831
4,59982.197226,5.040555,7.839388,4.23,26354.109472

In [ ]:
y.head()

0    1.059034e+06
1    1.505891e+06
2    1.058988e+06
3    1.260617e+06
4    6.309435e+05
Name: Price, dtype: float64

**Dividindo os dados em treino e teste**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=50)

In [ ]:
from sklearn.linear_model import LinearRegression

# Aqui criamos o modelo preditor
modelopreditor = LinearRegression()

# Aqui ocorre o aprendizado
modelopreditor.fit(X_train,y_train)

LinearRegression()

In [ ]:
# Imprimindo os coeficientes com os nomes das colunas
coeff = pd.DataFrame(modelopreditor.coef_,X.columns,columns=['Coeficiente'])
coeff

                                Coeficiente
Avg. Area Income                  21.525435
Avg. Area House Age           166415.114396
Avg. Area Number of Rooms     119802.717039
Avg. Area Number of Bedrooms    1783.166098
Area Population                   15.387540

In [ ]:
# fazendo predições com os dados de teste
predictions = modelopreditor.predict(X_test)

# imprimindo as primeiras variáveis preditoras
X_test.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population
3431,50570.864807,5.828143,4.851423,4.36,40580.092291
2042,65314.720112,6.918945,6.245656,2.42,36565.029831
79,64419.252638,6.954422,8.516160,6.16,39318.170755
4663,60390.502855,5.195406,8.368913,6.27,37921.720586
3640,73068.518101,7.271422,5.685408,3.14,42929.876157

In [ ]:
# Predições realizadas
predictions

array([ 631305.05842544, 1231990.56161569, 1539664.80551485, ...,
       1251986.62330197, 1036432.95159307, 1553580.80137907])

In [ ]:
# Valores reais para acertar
y_test.head()

3431    6.129387e+05
2042    1.347083e+06
79      1.492011e+06
4663    1.223915e+06
3640    1.368692e+06
Name: Price, dtype: float64

**AVALIANDO O MODELO**  
Aqui estão três métricas de avaliação comuns para problemas de regressão:  
• **Mean Absolute Error (MAE)** é a média do valor absoluto dos erros:  
• **Mean Squared Error (MSE)** é a média dos erros quadráticos:  
• **Root Mean Squared Error (RMSE)** é a raiz quadrada da média dos erros ao quadrado:  
Comparando estas métricas:  
• MAE é o mais fácil de entender, porque é o erro médio.  
• MSE é mais popular que o MAE, porque o MSE "pune" erros maiores, o que tende a ser útil no mundo real.  
• RMSE é ainda mais popular que o MSE, porque o RMSE é interpretável nas unidades do eixo "y".  
Todas essas são funções de perda, porque queremos minimizá-las.  
MAPE: erro médio absoluto em porcentagem

Para uma explicação sobre as várias métricas de avaliação, veja o artigo Métricas para Regressão: Entendendo as métricas R², MAE, MAPE, MSE e RMSE:

https://medium.com/data-hackers/prevendo-n%C3%BAmeros-entendendo-m%C3%A9tricas-de-regress%C3%A3o-35545e011e70

In [ ]:
from sklearn import metrics
print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))
print('MAPE:', metrics.mean_absolute_percentage_error(y_test, predictions))
print('R2:', metrics.r2_score(y_test, predictions))

MAE: 80728.93384538879
MSE: 10077066685.864893
RMSE: 100384.59386711137
MAPE: 0.0738402652144473
R2: 0.9186390166173336

---
**NORMALIZANDO**
---

In [ ]:
# Normalizando o dataframe
normalized_df=(df-df.min())/(df.max()-df.min())

In [ ]:
normalized_df.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
0,0.686822,0.441986,0.501502,0.464444,0.329942,0.425210
1,0.683521,0.488538,0.464501,0.242222,0.575968,0.607369
2,0.483737,0.468609,0.701350,0.695556,0.528582,0.425192
3,0.506630,0.660956,0.312430,0.280000,0.491549,0.507384
4,0.469223,0.348556,0.611851,0.495556,0.376988,0.250702

In [ ]:
normalized_df.describe()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,0.564890,0.484803,0.498658,0.440296,0.518234,0.495748
std,0.118547,0.144216,0.133694,0.274253,0.142920,0.143946
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.485889,0.389536,0.407138,0.253333,0.420903,0.400158
50%,0.567350,0.483815,0.500666,0.455556,0.518751,0.495992
75%,0.644977,0.582783,0.588787,0.553333,0.614676,0.593231
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
X_norm = normalized_df[['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms','Avg. Area Number of Bedrooms', 'Area Population']]
y_norm = normalized_df['Price']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_norm, y_norm, test_size=0.3, random_state=50)

In [ ]:
modelopreditor_norm = LinearRegression()
# Aqui ocorre o aprendizado
modelopreditor_norm.fit(X_train,y_train)
predictions = modelopreditor.predict(X_test)

In [ ]:
from sklearn import metrics
print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))
print('MAPE:', metrics.mean_absolute_percentage_error(y_test, predictions))
print('R2:', metrics.r2_score(y_test, predictions))

MAE: 2499708.265565341
MSE: 6249363584260.278
RMSE: 2499872.713611691
MAPE: 5651688.081964303
R2: -303639236966087.9